# -*- coding: utf-8 -*-
import translate
tr = translate.translate
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './fgfw-lite/ui\settings.ui'
#
# Created: Tue May 10 02:38:47 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(573, 435)
        Settings.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(Settings)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtGui.QTableView(Settings)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.parentRemoveButton = QtGui.QPushButton(Settings)
        self.parentRemoveButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.parentRemoveButton.setObjectName("parentRemoveButton")
        self.horizontalLayout_4.addWidget(self.parentRemoveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(12, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gfwlistToggle = QtGui.QCheckBox(Settings)
        self.gfwlistToggle.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gfwlistToggle.setObjectName("gfwlistToggle")
        self.horizontalLayout_6.addWidget(self.gfwlistToggle)
        self.updateToggle = QtGui.QCheckBox(Settings)
        self.updateToggle.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.updateToggle.setObjectName("updateToggle")
        self.horizontalLayout_6.addWidget(self.updateToggle)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.groupBox_2 = QtGui.QGroupBox(Settings)
        self.groupBox_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.ssNameEdit = QtGui.QLineEdit(self.groupBox_2)
        self.ssNameEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ssNameEdit.setObjectName("ssNameEdit")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.ssNameEdit)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.ssServerEdit = QtGui.QLineEdit(self.groupBox_2)
        self.ssServerEdit.setObjectName("ssServerEdit")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.ssServerEdit)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.ssPortEdit = QtGui.QLineEdit(self.groupBox_2)
        self.ssPortEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.ssPortEdit.setObjectName("ssPortEdit")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.ssPortEdit)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.ssMethodBox = QtGui.QComboBox(self.groupBox_2)
        self.ssMethodBox.setObjectName("ssMethodBox")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.ssMethodBox)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.ssPassEdit = QtGui.QLineEdit(self.groupBox_2)
        self.ssPassEdit.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.ssPassEdit.setObjectName("ssPassEdit")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.ssPassEdit)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.ssPriorityEdit = QtGui.QLineEdit(self.groupBox_2)
        self.ssPriorityEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhNoPredictiveText)
        self.ssPriorityEdit.setObjectName("ssPriorityEdit")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.ssPriorityEdit)
        self.verticalLayout_3.addLayout(self.formLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.shadowsocksAddButton = QtGui.QPushButton(self.groupBox_2)
        self.shadowsocksAddButton.setObjectName("shadowsocksAddButton")
        self.horizontalLayout_3.addWidget(self.shadowsocksAddButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.editConfButton = QtGui.QPushButton(Settings)
        self.editConfButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.editConfButton.setObjectName("editConfButton")
        self.horizontalLayout_2.addWidget(self.editConfButton)
        self.editLocalButton = QtGui.QPushButton(Settings)
        self.editLocalButton.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.editLocalButton.setObjectName("editLocalButton")
        self.horizontalLayout_2.addWidget(self.editLocalButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(tr("Settings", "设置", None, QtGui.QApplication.UnicodeUTF8))
        self.parentRemoveButton.setText(tr("Settings", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.gfwlistToggle.setText(tr("Settings", "gfwlist", None, QtGui.QApplication.UnicodeUTF8))
        self.updateToggle.setText(tr("Settings", "Auto Update", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(tr("Settings", "Shadowsocks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(tr("Settings", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(tr("Settings", "Hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(tr("Settings", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(tr("Settings", "Encryption", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(tr("Settings", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(tr("Settings", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.ssPriorityEdit.setText(tr("Settings", "99", None, QtGui.QApplication.UnicodeUTF8))
        self.shadowsocksAddButton.setText(tr("Settings", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.editConfButton.setText(tr("Settings", "Edit userconf.ini", None, QtGui.QApplication.UnicodeUTF8))
        self.editLocalButton.setText(tr("Settings", "Edit local.txt", None, QtGui.QApplication.UnicodeUTF8))

